apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  namespace: hotel-booking
  labels:
    app: hotel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
      - name: hotel-service
        image: hotel-service:latest
        imagePullPolicy: Never        
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        - secretRef:
            name: jwt-keys

---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
  namespace: hotel-booking
  labels:
    app: hotel-service
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: hotel-service
