apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-service
  namespace: hotel-booking
  labels:
    app: loyalty-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
    spec:
      containers:
      - name: loyalty-service
        image: loyalty-service:latest
        imagePullPolicy: Never        
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        - secretRef:
            name: jwt-keys

---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-service
  namespace: hotel-booking
  labels:
    app: loyalty-service
spec:
  ports:
  - port: 8085
    targetPort: 8085
  selector:
    app: loyalty-service
