apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: hotel-booking
  labels:
    app: session-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: session-service
        image: session-service:latest
        imagePullPolicy: Never        
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        - secretRef:
            name: jwt-keys
        env:
        - name: server.port
          value: "8081"

---
apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: hotel-booking
  labels:
    app: session-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: session-service
